import { auditLogs, categories, hotels, memberships, menu, notifications, orders, payments, tables } from "@/lib/mock-data/admin";
import type { ResourceConfig } from "@/components/dashboard/ResourcePage";

export const resourceConfigs:Record<string,ResourceConfig> = {
  orders:{title:"Orders",description:"Track, manage, and fulfil every guest order.",singular:"order",rows:orders,detailBase:"/dashboard/orders",filter:{key:"status",label:"Status",options:["Pending","Preparing","Ready","Completed","Cancelled"]},columns:[{key:"id",label:"Order"},{key:"customer",label:"Customer"},{key:"table",label:"Table"},{key:"type",label:"Type"},{key:"status",label:"Status",badge:true},{key:"total",label:"Total"},{key:"payment",label:"Payment",badge:true},{key:"created",label:"Created"}],fields:[{key:"customer",label:"Customer name"},{key:"table",label:"Table"},{key:"type",label:"Order type",type:"select",options:["Dine In","Takeaway","Delivery"]},{key:"status",label:"Status",type:"select",options:["Pending","Preparing","Ready","Completed","Cancelled"]},{key:"total",label:"Total amount"},{key:"payment",label:"Payment",type:"select",options:["Pending","Paid","Failed","Refunded"]},{key:"created",label:"Created date"}]},
  tables:{title:"Dining tables",description:"Manage floor availability, capacity, and service status.",singular:"table",rows:tables,filter:{key:"status",label:"Status",options:["Available","Occupied","Reserved","Cleaning","Inactive"]},columns:[{key:"number",label:"Table"},{key:"capacity",label:"Capacity"},{key:"status",label:"Status",badge:true},{key:"order",label:"Current order"},{key:"section",label:"Section"},{key:"created",label:"Created"}],fields:[{key:"number",label:"Table number"},{key:"capacity",label:"Capacity",type:"number"},{key:"status",label:"Status",type:"select",options:["Available","Occupied","Reserved","Cleaning","Inactive"]},{key:"order",label:"Current order"},{key:"section",label:"Section"},{key:"created",label:"Created date"}]},
  hotels:{title:"Hotels & restaurants",description:"Manage your hospitality locations and contact details.",singular:"hotel",rows:hotels,columns:[{key:"name",label:"Name"},{key:"location",label:"Location"},{key:"phone",label:"Phone"},{key:"email",label:"Email"},{key:"status",label:"Status",badge:true},{key:"created",label:"Created"}],fields:[{key:"name",label:"Name"},{key:"location",label:"Location"},{key:"phone",label:"Phone"},{key:"email",label:"Email",type:"email"},{key:"status",label:"Status",type:"select",options:["Active","Inactive"]},{key:"created",label:"Created date"}]},
  memberships:{title:"Memberships",description:"Manage staff access, roles, and assigned locations.",singular:"member",rows:memberships,filter:{key:"role",label:"Role",options:["Owner","Admin","Manager","Cashier","Waiter","Kitchen Staff"]},columns:[{key:"name",label:"Staff member"},{key:"email",label:"Email"},{key:"role",label:"Role",badge:true},{key:"hotel",label:"Location"},{key:"status",label:"Status",badge:true},{key:"joined",label:"Joined"}],fields:[{key:"name",label:"Staff name"},{key:"email",label:"Email",type:"email"},{key:"role",label:"Role",type:"select",options:["Owner","Admin","Manager","Cashier","Waiter","Kitchen Staff"]},{key:"hotel",label:"Hotel / restaurant"},{key:"status",label:"Status",type:"select",options:["Active","Inactive"]},{key:"joined",label:"Joined date"}]},
  categories:{title:"Menu categories",description:"Organise dishes into clear, guest-friendly collections.",singular:"category",rows:categories,columns:[{key:"name",label:"Name"},{key:"description",label:"Description"},{key:"items",label:"Items"},{key:"status",label:"Status",badge:true},{key:"created",label:"Created"}],fields:[{key:"name",label:"Name"},{key:"description",label:"Description",type:"textarea"},{key:"items",label:"Number of items",type:"number"},{key:"status",label:"Status",type:"select",options:["Active","Inactive"]},{key:"created",label:"Created date"}]},
  menu:{title:"Menu items",description:"Create, price, and manage dishes across the menu.",singular:"menu item",rows:menu,filter:{key:"category",label:"Category",options:["Starters","Mains","Desserts","Seasonal"]},columns:[{key:"name",label:"Item"},{key:"category",label:"Category"},{key:"price",label:"Price"},{key:"availability",label:"Availability",badge:true},{key:"prepTime",label:"Prep time"},{key:"description",label:"Description"}],fields:[{key:"name",label:"Name"},{key:"description",label:"Description",type:"textarea"},{key:"category",label:"Category",type:"select",options:["Starters","Mains","Desserts","Seasonal"]},{key:"price",label:"Price"},{key:"image",label:"Image URL"},{key:"prepTime",label:"Preparation time"},{key:"availability",label:"Availability",type:"select",options:["Available","Unavailable"]}]},
  payments:{title:"Payments",description:"Review transactions, methods, and settlement status.",singular:"payment",rows:payments,filter:{key:"status",label:"Status",options:["Pending","Paid","Failed","Refunded"]},columns:[{key:"id",label:"Payment"},{key:"orderId",label:"Order"},{key:"customer",label:"Customer"},{key:"amount",label:"Amount"},{key:"method",label:"Method",badge:true},{key:"status",label:"Status",badge:true},{key:"date",label:"Date"}],fields:[{key:"orderId",label:"Order ID"},{key:"customer",label:"Customer"},{key:"amount",label:"Amount"},{key:"method",label:"Method",type:"select",options:["Cash","Card","M-Pesa","Bank Transfer"]},{key:"status",label:"Status",type:"select",options:["Pending","Paid","Failed","Refunded"]},{key:"date",label:"Date"}]},
  notifications:{title:"Notifications",description:"Create and manage operational alerts for your team.",singular:"notification",rows:notifications,filter:{key:"type",label:"Type",options:["Order","Payment","System","Table","Membership"]},columns:[{key:"title",label:"Title"},{key:"message",label:"Message"},{key:"type",label:"Type",badge:true},{key:"status",label:"Status",badge:true},{key:"created",label:"Created"}],fields:[{key:"title",label:"Title"},{key:"message",label:"Message",type:"textarea"},{key:"type",label:"Type",type:"select",options:["Order","Payment","System","Table","Membership"]},{key:"status",label:"Status",type:"select",options:["Read","Unread"]},{key:"created",label:"Created date"}]},
  audits:{title:"Audit logs",description:"A read-only history of account and operational activity.",singular:"log",rows:auditLogs,readOnly:true,filter:{key:"resource",label:"Resource",options:["Order","Menu Item","Table","Payment","Membership"]},columns:[{key:"user",label:"User"},{key:"action",label:"Action",badge:true},{key:"resource",label:"Resource"},{key:"resourceId",label:"Resource ID"},{key:"description",label:"Description"},{key:"ip",label:"IP address"},{key:"date",label:"Date"}],fields:[]},
};
